behaviors:
  Pixel:
    trainer_type: poca
    hyperparameters:
      batch_size: 8192
      buffer_size: 81920
      learning_rate: 0.0002
      beta: 0.003
      epsilon: 0.8
      lambd: 0.93
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 175000000
    time_horizon: 100
    summary_freq: 20000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 10000
      team_change: 200000
